name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'
        if: ${{ github }}
      - run: echo '${{ github && steps }}'
      - run: echo '${{ !!42 }}'
      - run: echo '${{ format(null) }}'
      - run: echo '${{ format(true) }}'
